extends Node

var data={
	#block
		#wood
	"wood":{"name":"wood_board","num":2},
	"wood_stick":{"name":"transmission_wood_stick","num":1},
	"wood_board":{"name":"button","num":1},
	"2wood_board,4wood_board,6wood_board,8wood_board":{"name":"wood_gear","num":1},
	
		#wood_board
	"1wood_board,2wood_board,4wood_board,5wood_board":{"name":"workbench","num":1},
	"wood_board,3wood_board":{"name":"wood_stick","num":4},
	"1wood_board,2wood_board,3wood_board,4wood_board,6wood_board,7wood_board,8wood_board,9wood_board":{"name":"wood_box","num":1},
	"wood_stick,3crushed_stone":{"name":"pull_rod","num":1},
	"wood_board,1wood_board,3wood_board,4wood_board,6wood_board,7wood_board":{"name":"door","num":1},
	"4wood_board,6wood_board,8wood_board":{"name":"wood_bowl","num":1},
	"1wood_board,3wood_board,4wood_board,6wood_board,7wood_board,8wood_board,9wood_board":{"name":"wood_barrel","num":1},
	"coal,3wood_stick":{"name":"torch","num":2},
	"charcoal,3wood_stick":{"name":"torch","num":2},
		#other
	"wood_stick,2wood_stick,3wood_stick,4wood_stick,5wood_stick,6wood_stick,8wood_stick":{"name":"ladder","num":2},
	"1wood_board,2wood_barrel,3wood_board,4wood_board,5wood_barrel,6wood_board,7wood_board,8wood_board,9wood_board":{"name":"wood_vat","num":1},
		#iron
	"1iron_ingot,3iron_ingot,4iron_ingot,6iron_ingot,8iron_ingot":{"name":"funnel","num":1},
	#tool
		#wood_board tool
	"wood_board,3wood_board,6wood_stick":{"name":"wood_sword","num":1},
	"1wood_board,2wood_board,3wood_board,5wood_stick,8wood_stick":{"name":"wood_pickaxe","num":1},
	"wood_board,1wood_board,3wood_board,4wood_stick,7wood_stick":{"name":"wood_axe","num":1},
	"wood_board,1wood_board,4wood_stick,7wood_stick":{"name":"wood_hoe","num":1},
	"wood_board,3wood_stick,6wood_stick":{"name":"wood_shovel","num":1},
	"7wood_board,8wood_board,9wood_board":{"name":"pressure_board","num":2},
		#stone tool 
	"crushed_stone,3crushed_stone,6wood_stick":{"name":"stone_sword","num":1},
	"1crushed_stone,2crushed_stone,3crushed_stone,5wood_stick,8wood_stick":{"name":"stone_pickaxe","num":1},
	"crushed_stone,1crushed_stone,3crushed_stone,4wood_stick,7wood_stick":{"name":"stone_axe","num":1},
	"crushed_stone,1crushed_stone,4wood_stick,7wood_stick":{"name":"stone_hoe","num":1},
	"crushed_stone,3wood_stick,6wood_stick":{"name":"stone_shovel","num":1},
	"1crushed_stone,2crushed_stone,3crushed_stone,4crushed_stone,6crushed_stone,7crushed_stone,8crushed_stone,9crushed_stone":{"name":"stone_stove","num":1},
		#copper
	"copper_ingot,3copper_ingot,6wood_stick":{"name":"copper_sword","num":1},
	"1copper_ingot,2copper_ingot,3copper_ingot,5wood_stick,8wood_stick":{"name":"copper_pickaxe","num":1},
	"copper_ingot,1copper_ingot,3copper_ingot,4wood_stick,7wood_stick":{"name":"copper_axe","num":1},
	"copper_ingot,1copper_ingot,4wood_stick,7wood_stick":{"name":"copper_hoe","num":1},
	"copper_ingot,3wood_stick,6wood_stick":{"name":"copper_shovel","num":1},
	"1copper_ingot,3copper_ingot,5copper_ingot,8copper_ingot":{"name":"copper_wrench","num":1},
		#bronze
	"bronze_ingot,3bronze_ingot,6wood_stick":{"name":"bronze_sword","num":1},
	"1bronze_ingot,2bronze_ingot,3bronze_ingot,5wood_stick,8wood_stick":{"name":"bronze_pickaxe","num":1},
	"bronze_ingot,1bronze_ingot,3bronze_ingot,4wood_stick,7wood_stick":{"name":"bronze_axe","num":1},
	"bronze_ingot,1bronze_ingot,4wood_stick,7wood_stick":{"name":"bronze_hoe","num":1},
	"bronze_ingot,3wood_stick,6wood_stick":{"name":"bronze_shovel","num":1},
	"1bronze_ingot,3bronze_ingot,5bronze_ingot,8bronze_ingot":{"name":"bronze_wrench","num":1},
		#iron
	"iron_ingot,3iron_ingot,6wood_stick":{"name":"iron_sword","num":1},
	"1iron_ingot,2iron_ingot,3iron_ingot,5wood_stick,8wood_stick":{"name":"iron_pickaxe","num":1},
	"iron_ingot,1iron_ingot,3iron_ingot,4wood_stick,7wood_stick":{"name":"iron_axe","num":1},
	"iron_ingot,1iron_ingot,4wood_stick,7wood_stick":{"name":"iron_hoe","num":1},
	"iron_ingot,3wood_stick,6wood_stick":{"name":"iron_shovel","num":1},
	"1iron_ingot,3iron_ingot,5iron_ingot,8iron_ingot":{"name":"iron_wrench","num":1},
		#silver
	"silver_ingot,3silver_ingot,6wood_stick":{"name":"silver_sword","num":1},
	"1silver_ingot,2silver_ingot,3silver_ingot,5wood_stick,8wood_stick":{"name":"silver_pickaxe","num":1},
	"silver_ingot,1silver_ingot,3silver_ingot,4wood_stick,7wood_stick":{"name":"silver_axe","num":1},
	"silver_ingot,1silver_ingot,4wood_stick,7wood_stick":{"name":"silver_hoe","num":1},
	"silver_ingot,3wood_stick,6wood_stick":{"name":"silver_shovel","num":1},
		#gold
	"gold_ingot,3gold_ingot,6wood_stick":{"name":"gold_sword","num":1},
	"1gold_ingot,2gold_ingot,3gold_ingot,5wood_stick,8wood_stick":{"name":"gold_pickaxe","num":1},
	"gold_ingot,1gold_ingot,3gold_ingot,4wood_stick,7wood_stick":{"name":"gold_axe","num":1},
	"gold_ingot,1gold_ingot,4wood_stick,7wood_stick":{"name":"gold_hoe","num":1},
	"gold_ingot,3wood_stick,6wood_stick":{"name":"gold_shovel","num":1},
		#steel
	"steel_ingot,3steel_ingot,6wood_stick":{"name":"steel_sword","num":1},
	"1steel_ingot,2steel_ingot,3steel_ingot,5wood_stick,8wood_stick":{"name":"steel_pickaxe","num":1},
	"steel_ingot,1steel_ingot,3steel_ingot,4wood_stick,7wood_stick":{"name":"steel_axe","num":1},
	"steel_ingot,1steel_ingot,4wood_stick,7wood_stick":{"name":"steel_hoe","num":1},
	"steel_ingot,3wood_stick,6wood_stick":{"name":"steel_shovel","num":1},
	"1steel_ingot,3steel_ingot,5steel_ingot,8steel_ingot":{"name":"steel_wrench","num":1},
		#diamond
	"diamond,3diamond,6wood_stick":{"name":"diamond_sword","num":1},
	"1diamond,2diamond,3diamond,5wood_stick,8wood_stick":{"name":"diamond_pickaxe","num":1},
	"diamond,1diamond,3diamond,4wood_stick,7wood_stick":{"name":"diamond_axe","num":1},
	"diamond,1diamond,4wood_stick,7wood_stick":{"name":"diamond_hoe","num":1},
	"diamond,3wood_stick,6wood_stick":{"name":"diamond_shovel","num":1},
	#food
	"wheat":{"name":"flour","num":1},
	"paddy":{"name":"rice_shell","num":1},
	"rice_shell":{"name":"rice","num":1},
	"wood_bowl_water,flour":{"name":"dough","num":1,"put":["wood_bowl"]},
	"wood_bowl,herb":{"name":"wood_bowl_herb","num":1},
	#book
	"4wood_board,5wood_board,6wood_board":{"name":"paper","num":3},
	"4paper,5paper,6paper":{"name":"book","num":1},
	"7paper,8paper,9paper":{"name":"all_compound_book","num":1},
	
}