extends Node
var data={
	"grass_dirt":"block",
	"dirt":"block",
	"dirt_plow":"block",
	"sand":"block",
	"copper_ore":"block",
	"tin_ore":"block",
	"zinc_ore":"block",
	"iron_ore":"block",
	"coal_ore":"block",
	"diamond_ore":"block",
	"silver_ore":"block",
	"gold_ore":"block",
	"stone":"block",
	"crushed_stone":"block",
	"relic_stone":"block",
	"leaf":"block",
	"leaf_dead":"block",
	"wood":"block",
	"wood_board":"block",
	"workbench":"block",
	"wood_box":"block",
	"stone_stove":"block",
	"unknown_block":"block",
	
	#plant
#	"herb_status0":"block",
#	"herb_status1":"block",
#	"herb_status2":"block",
#	"paddy_status0":"block",
#	"paddy_status1":"block",
#	"paddy_status2":"block",
#	"paddy_status3":"block",
#	"wheat_status0":"block",
#	"wheat_status1":"block",
#	"wheat_status2":"block",
#	"wheat_status3":"block",
	
	
	#家具
	"door":"block",
	"door0":"block",
	"ladder":"block",
	"wood_vat":"block",
	"funnel":"block",
	#big block
	"big_stone_stove":"block",
	"big_stone_stove_wall":"block",
	"high_stone_stove":"block",
	#gear
	"wood_gear":"gear",
	#switch
	"button":"switch",	
	"pull_rod":"switch",
	"pressure_board":"switch",
	#item
	"transmission_wood_stick":"item",
	#ingot
	"copper_ingot":"item",
	"bronze_ingot":"item",
	"tin_ingot":"item",
	"zinc_ingot":"item",
	"iron_ingot":"item",
	"steel_ingot":"item",
	"silver_ingot":"item",
	"gold_ingot":"item",
	"diamond":"item",
	
	
	

	"book":"item",
	"paper":"item",
	"wood_stick":"item",
	"coal":"item",
	"charcoal":"item",
	"wheat":"item",

	#seed
	"wheat_seed":"seed",
	"paddy_seed":"seed",
	"oak_seed":"seed",
	"herb":"seed",
	#liquid
	"water_deep":"liquid",
	"water":"liquid",
	

	#function_item
	"all_compound_book":"func_item",
	"wood_bowl":"func_items",
	"wood_bowl_water":"func_item",
	"wood_barrel":"func_items",
	"wood_barrel_water":"func_item",
	"wood_bowl_herb":"func_items",
	#tool
		#axe
	"wood_axe":"tool",
	"stone_axe":"tool",
	"copper_axe":"tool",
	"bronze_axe":"tool",
	"iron_axe":"tool",
	"steel_axe":"tool",
	"silver_axe":"tool",
	"gold_axe":"tool",
	"diamond_axe":"tool",
		#pickaxe
	"wood_pickaxe":"tool",
	"stone_pickaxe":"tool",
	"copper_pickaxe":"tool",
	"bronze_pickaxe":"tool",
	"iron_pickaxe":"tool",
	"steel_pickaxe":"tool",
	"silver_pickaxe":"tool",
	"gold_pickaxe":"tool",
	"diamond_pickaxe":"tool",
		#hoe
	"wood_hoe":"tool",
	"stone_hoe":"tool",
	"copper_hoe":"tool",
	"bronze_hoe":"tool",
	"iron_hoe":"tool",
	"steel_hoe":"tool",
	"silver_hoe":"tool",
	"gold_hoe":"tool",
	"diamond_hoe":"tool",
		#sword
	"wood_sword":"tool",
	"stone_sword":"tool",
	"copper_sword":"tool",
	"bronze_sword":"tool",
	"iron_sword":"tool",
	"steel_sword":"tool",
	"silver_sword":"tool",
	"gold_sword":"tool",
	"diamond_sword":"tool",
		#shovel
	"wood_shovel":"tool",
	"stone_shovel":"tool",
	"copper_shovel":"tool",
	"bronze_shovel":"tool",
	"iron_shovel":"tool",
	"steel_shovel":"tool",
	"silver_shovel":"tool",
	"gold_shovel":"tool",
	"diamond_shovel":"tool",
		#wrench
	"copper_wrench":"tool",
	"bronze_wrench":"tool",
	"iron_wrench":"tool",
	"steel_wrench":"tool",
	#light
	"torch":"light",
	#food
	"apple":"food",
	"wheat":"item",
	"flour":"item",
	"dough":"item",
	"steamed_bread":"food",
	"bread":"food",
	"paddy":"item",
	"rice_shell":"item",
	"rice":"item",
	"rice_ball":"food",
	"clam":"food",
	"clam_ripe":"food",
	"pig_meat":"food",
	"pig_meat_cook":"food",
}